version: '3.8'

volumes:
  postgres_data: { }

services:
  fastapi:
    container_name: fastapi_backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:80"
    command: /start_reload.sh
    env_file:
      - .env
    networks:
      - ylab_network

  postgres:
    container_name: main_db
    restart: always
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD", "pg_isready" , "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}" ]
      interval: 10s
      timeout: 20s
      retries: 5
    env_file:
      - .env
    networks:
      - ylab_network

networks:
  ylab_network:
    driver: bridge
