version: '3.8'

volumes:
  postgres_data: { }
  redis_cache_data: { }

services:
  fastapi:
    container_name: fastapi_backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy
      redis_cache:
        condition: service_healthy
    ports:
      - "8000:80"
    command: /start_reload.sh
    env_file:
      - .env
    networks:
      - ylab_network

  postgres:
    container_name: main_db
    restart: always
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD", "pg_isready" , "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}" ]
      interval: 10s
      timeout: 20s
      retries: 5
    env_file:
      - .env
    networks:
      - ylab_network

  redis_cache:
    container_name: redis_cache
    image: redis:7.0
    restart: always
    ports:
      - '${REDIS_CACHE_PORT}:${REDIS_CACHE_PORT}'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_CACHE_PASSWORD}
    volumes:
      - redis_cache_data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_CACHE_PASSWORD}
      - REDIS_HOST=${REDIS_CACHE_HOST}
      - REDIS_PORT=${REDIS_CACHE_PORT}
    env_file:
      - .env
    healthcheck:
      test: redis-cli -a ${REDIS_CACHE_PASSWORD} -p ${REDIS_CACHE_PORT} ping | grep PONG
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 30s
    networks:
      - ylab_network


networks:
  ylab_network:
    driver: bridge
