version: '3.8'

volumes:
  postgres_data: { }
  redis_cache_data: { }


services:
  fastapi:
    container_name: "ylab_fastapi_backend"
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy
      redis_cache:
        condition: service_healthy
      rabbitmq3:
        condition: service_healthy
    ports:
      - "8000:80"
    command: /start_reload.sh
    env_file:
      - .env
    networks:
      - ylab_network

  postgres:
    container_name: "ylab_main_db"
    restart: always
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD", "pg_isready" , "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}" ]
      interval: 10s
      timeout: 20s
      retries: 5
    env_file:
      - .env
    networks:
      - ylab_network

  redis_cache:
    container_name: "ylab_redis_cache"
    image: redis:7.0
    restart: always
    ports:
      - '${REDIS_CACHE_PORT}:${REDIS_CACHE_PORT}'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_CACHE_PASSWORD}
    volumes:
      - redis_cache_data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_CACHE_PASSWORD}
      - REDIS_HOST=${REDIS_CACHE_HOST}
      - REDIS_PORT=${REDIS_CACHE_PORT}
    env_file:
      - .env
    healthcheck:
      test: redis-cli -a ${REDIS_CACHE_PASSWORD} -p ${REDIS_CACHE_PORT} ping | grep PONG
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 30s
    networks:
      - ylab_network

  celery:
    container_name: "ylab_celery_worker"
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A workers.celery_worker worker -B --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - ylab_network
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq3:
        condition: service_healthy
      redis_cache:
        condition: service_healthy

  rabbitmq3:
    container_name: "ylab_rabbitmq3"
    restart: always
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    env_file:
      - .env
    networks:
      - ylab_network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 20s
      timeout: 20s
      retries: 3

networks:
  ylab_network:
    driver: bridge
