name: Docker Compose Test Actions Workflow

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: | 
          chmod +x run_tests.sh
          bash run_tests.sh
