name: Docker Compose Test Actions Workflow

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Up test environment
        run: |
          cp .env_test .env
          docker compose -f docker-compose.yml up -d --build
      - name: Test
        run: docker exec fastapi_backend python3 -m pytest -v
      - name: Down test environment
        run: docker compose -f docker-compose.yml down
